### ISSUE TITLE
pypassport broken with recent crypto lib

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oroger/pypassport#1]
```
Since a recent python crypto lib, IV is now mandatory for DES3.
See patch in attachment.

```

Original issue reported on code.google.com by `yob...@gmail.com` on 16 Jan 2013 at 11:06

Attachments:
- [pypassport-des3-iv.patch](https://storage.googleapis.com/google-code-attachments/pypassport/issue-1/comment-0/pypassport-des3-iv.patch)

**Comment by oroger** [comment]
Thank you for the path !
